kuka_lbr_iiwa_14_r820:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # trajectory controllers for RIGHT ARM
  tr_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7

    gains: 
      joint_a1: {p: 800.0, i: 100.0, d: 80.0, i_clamp: 10000.0}
      joint_a2: {p: 1000.0, i: 1000.0, d: 80.0, i_clamp: 10000.0}
      joint_a3: {p: 800.0, i: 10.0, d: 20.0, i_clamp: 10000.0}
      joint_a4: {p: 800.0, i: 500.0, d: 50.0, i_clamp: 10000.0}
      joint_a5: {p: 300.0, i: 5.0, d: 10.0, i_clamp: 10000.0}
      joint_a6: {p: 50.0, i: 1.0, d: 1.0, i_clamp: 500.0}
      joint_a7: {p: 20.0, i: 0.2, d: 1.0, i_clamp: 500.0}